[package]
name = "rustbot2"
version = "0.1.0"
edition = "2021"

[features]
integration = []

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1"
futures = "0.3"
rustbot2-macros = { path = "../rustbot2-macros" }

[dev-dependencies]
testcontainers = "0.23"
irc = { version = "1", default-features = false }

[[example]]
name = "basic_bot"
