[package]
name = "ircbot"
version = "0.1.0"
edition = "2021"

[features]
integration = []

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1"
futures = "0.3"
ircbot-macros = { path = "../ircbot-macros" }
irc-proto = { version = "1", default-features = false }

[dev-dependencies]
testcontainers = "0.27"
irc = { version = "1", default-features = false }

[[example]]
name = "basic_bot"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
